[mypy]
python_version = 3.11
plugins = mypy_django_plugin.main
ignore_missing_imports = True
strict = False

# Ajustes del plugin django-stubs
[mypy.plugins.django-stubs]
django_settings_module = "core.settings"  # <- cambia si usás otro path